// packages/ui/components/albums/albumCard.vue
<script setup lang="ts">
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

import { Play } from 'lucide-vue-next';
import type { AlbumDetailResponse, AlbumResponse } from '@music/api/dto/album.dto';
import { useAudioPlayerStore } from '../../stores/audioPlayer';
import { parsePlaylistFromAlbumDetail } from '../../lib/music/parse';
import type { PropType } from 'vue';
import { navigateTo } from 'nuxt/app';

const player = useAudioPlayerStore();

const props = defineProps({
    album: {
        type: Object as () => AlbumResponse,
        required: true,
    },
    getAlbumInfo: {
        type: Function as PropType<(albumID: string) => Promise<AlbumDetailResponse>>,
        required: true,
    }
});

const clickPlay = async (albumID: string) => {
    const albumInfo = await props.getAlbumInfo(albumID);
    const playList = parsePlaylistFromAlbumDetail(albumInfo);
    player.playWithList(playList);
}

function handleAlbumClick(id: string) {
    return navigateTo({
        path: `/music/albums/${id}`,
    })
}

</script>


<template>
    <Card v-if="props.album" @click="handleAlbumClick(props.album.id)"
        class="group hover:bg-muted transition-all duration-300 hover:scale-105 hover:shadow-2xl border-0 rounded-lg overflow-hidden cursor-pointer">
        <CardContent>
            <div class="aspect-square relative overflow-hidden">
                <img v-if="props.album.cover" :src="props.album.cover" alt="" class="w-full h-full object-cover" />
                <div v-else>

                </div>

                <Button size="icon" @click.stop="clickPlay(props.album.id)"
                    class="absolute bottom-4 right-4 w-12 h-12 rounded-full bg-primary shadow-lg opacity-0 group-hover:opacity-100 translate-y-2 group-hover:translate-y-0 transition-all duration-300 cursor-pointer">
                    <Play
                        class="w-5 h-5 fill-primary-foreground text-primary-foreground ml-0.5 hover:fill-primary-foreground/20" />
                </Button>
            </div>
            <div class="p-4 space-y-1">
                <h3 class="text-lg font-semibold text-foreground truncate">{{ props.album.name }}</h3>
                <p class="text-sm text-muted-foreground">{{ props.album.mainArtist.name }}</p>
                <p class="text-sm text-muted-foreground"><span v-if="props.album.year != 0">{{ props.album.year }}
                        •</span>
                    {{ props.album.totalTracks }} songs</p>
            </div>
        </CardContent>
    </Card>
</template>

// apps/web/src/components/albumCard.tsx
import { Link } from "@tanstack/react-router";
import type { components } from "@/data/APIschema";
import { cn } from "@/lib/utils/style";
import { Badge } from "./shadcn/badge";
import { Card } from "./shadcn/card";

type AlbumCardProps = {
	album: components["schemas"]["AlbumListItemModel"];
	className?: string;
};

export function AlbumCard({ album, className }: AlbumCardProps) {
	return (
		<Link to="/albums/$id" params={{ id: album.albumId.toString() }}>
			<Card className={cn("relative mx-auto w-full max-w-96 pt-0", className)}>
				{album.coverVariants ? (
					<div className="relative aspect-square overflow-hidden bg-muted">
						<img
							src={album.coverVariants?.[0]?.url}
							alt={`${album.title} album cover`}
							className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
						/>
						<Badge className="absolute right-2 top-2 bg-black/60 backdrop-blur-sm">
							{album.type}
						</Badge>
					</div>
				) : (
					<div></div>
				)}
				<div className="space-y-2 pl-4">
					<h3 className="line-clamp-2 text-balance font-semibold leading-tight">
						{album.title}
					</h3>
					<p className="text-sm text-muted-foreground line-clamp-3">
						{album.artists.map((artist) => artist.name).join(", ")}
					</p>
					<p className="text-xs text-muted-foreground">
						{album.trackCount} songs
					</p>
				</div>
			</Card>
		</Link>
	);
}
