// apps/web/src/app/components/music/albums/albumCard.vue
<script setup lang="ts">
import { DiscAlbum, Play } from 'lucide-vue-next';
import type { AlbumResponse } from '@music/api/dto/album.dto'

const props = defineProps({
    album: {
        type: Object as () => AlbumResponse,
        required: true
    }
})

function handleAlbumClick() {
    return navigateTo({
        path: `/music/albums/${props.album.id}`,
    })
}

</script>

<template>
    <Card @click="handleAlbumClick"
        class="group hover:bg-muted transition-all duration-300 hover:scale-105 hover:shadow-2xl border-0 rounded-lg cursor-pointer">
        <CardContent>
            <div class="aspect-square relative overflow-hidden">
                <img v-if="album.cover" :src="album.cover" class="w-full h-full object-cover" />
                <DiscAlbum v-else class="w-full h-full text-muted-foreground" />
                <Badge variant="secondary"
                    class="absolute top-2 right-2 bg-black/60 text-white border-0 backdrop-blur-sm">
                    {{ album.albumType }}
                </Badge>
                <Button size="icon"
                    class="absolute bottom-4 right-4 w-12 h-12 rounded-full bg-primary shadow-lg opacity-0 group-hover:opacity-100 translate-y-2 group-hover:translate-y-0 transition-all duration-300 cursor-pointer">
                    <Play
                        class="w-5 h-5 fill-primary-foreground text-primary-foreground ml-0.5 hover:fill-primary-foreground/20" />
                </Button>
            </div>
            <div class="p-4 space-y-1">
                <h3 class="text-lg font-semibold text-foreground truncate">{{ album.name }}</h3>
                <p class="text-sm text-muted-foreground">{{ album.mainArtist.name }}</p>
                <div class="flex gap-1 flex-wrap">
                    <Badge v-if="album.hasInstrumental" variant="outline" class="opacity-60">
                        Instrumental
                    </Badge>
                </div>
                <p class="text-sm text-muted-foreground"><span v-if="album.year != 0">{{ album.year }}
                        •</span>
                    {{ album.totalTracks }} songs</p>
            </div>
        </CardContent>
    </Card>
</template>

// apps/web/src/components/albumCard.tsx
import { Link } from "@tanstack/react-router";
import type { components } from "@/data/APIschema";
import { Badge } from "./shadcn/badge";
import { Card } from "./shadcn/card";

type AlbumCardProps = {
	album: components["schemas"]["AlbumListItemModel"];
};

export function AlbumCard({ album }: AlbumCardProps) {
	return (
		<Link to="/albums/$id" params={{ id: album.albumId.toString() }}>
			<Card className="relative mx-auto w-full max-w-70 pt-0">
				{album.coverVariants ? (
					<div className="relative aspect-square overflow-hidden bg-muted">
						<img
							src={album.coverVariants?.[0]?.url}
							alt={`${album.title} album cover`}
							className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
						/>
						<Badge className="absolute right-2 top-2 bg-black/60 backdrop-blur-sm">
							{album.type}
						</Badge>
					</div>
				) : (
					<div></div>
				)}
				<div className="space-y-2 pl-4">
					<h3 className="line-clamp-2 text-balance font-semibold leading-tight">
						{album.title}
					</h3>
					<p className="text-sm text-muted-foreground line-clamp-1">
						{album.artists.map((artist) => artist.name).join(", ")}
					</p>
					<p className="text-xs text-muted-foreground">
						{album.trackCount} songs
					</p>
				</div>
			</Card>
		</Link>
	);
}
