// packages/ui/components/ui/label/Label.vue
<script setup lang="ts">
import type { LabelProps } from "reka-ui"
import { reactiveOmit } from "@vueuse/core"
import { Label } from "reka-ui"
import { cn } from "@/lib/utils"

const props = defineProps<LabelProps & { class?: string }>()

const delegatedProps = reactiveOmit(props, "class")
</script>

<template>
  <Label
    data-slot="label"
    v-bind="delegatedProps"
    :class="
      cn(
        'flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50',
        props.class,
      )
    "
  >
    <slot />
  </Label>
</template>

// apps/web/src/components/coss/label.tsx
import { mergeProps } from "@base-ui/react/merge-props";
import { useRender } from "@base-ui/react/use-render";
import type React from "react";

import { cn } from "@/lib/utils/styles";

export function Label({
	className,
	render,
	...props
}: useRender.ComponentProps<"label">): React.ReactElement {
	const defaultProps = {
		className: cn(
			"inline-flex items-center gap-2 text-base/4.5 font-medium text-foreground sm:text-sm/4",
			className,
		),
		"data-slot": "label",
	};

	return useRender({
		defaultTagName: "label",
		props: mergeProps<"label">(defaultProps, props),
		render,
	});
}
